### ISSUE TITLE
Add Support for Android API 21

### ISSUE THREAD

**Issue by Napharcos** [Appstractive/dns-sd-kt#12]
Currently, the minimum API level for this project is set to 24, but I need support for API 21.

This would require only minor changes.

libs.verions.toml:
```
[versions]
...
library-desugaring = "2.1.3"

[libraries]
...
library-desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "library-desugaring" }
...
```

build.gradle.kts:
```
...
kotlin {
  androidTarget {
    publishAllLibraryVariants()
    compilations.all { kotlinOptions { jvmTarget = "1.8" } }
  }
...
}

android {
...
defaultConfig {  minSdk = 21  }
...
compileOptions {
    isCoreLibraryDesugaringEnabled = true

    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
}

dependencies {
  coreLibraryDesugaring(libs.library.desugaring)
}
...
```

[source](https://developer.android.com/studio/write/java8-support#library-desugaring)

**Comment by Napharcos** [comment]
Not necessary, this will solve the problem:

AndroidManifest.xml
```
    <uses-sdk
        android:minSdkVersion="21"
        tools:overrideLibrary="com.appstractive.dnssd" />
```

**Comment by aschulz90** [comment]
Have you checked this on a real device with sdk21? I will look into implementing your suggestion, so that workaround wouldn't be needed then.

**Comment by Napharcos** [comment]
Only on emulator for now, but it works there.

**Comment by Napharcos** [comment]
```
private fun NsdServiceInfo.getAddresses(): List<String> {
  if (VERSION.SDK_INT >= VERSION_CODES.UPSIDE_DOWN_CAKE) {
    return hostAddresses.mapNotNull { it.hostAddress }
  }

  return host.hostAddress?.let { listOf(it) } ?: emptyList()
}

private fun NsdServiceInfo.getHostName(): String? {
  if (VERSION.SDK_INT >= VERSION_CODES.UPSIDE_DOWN_CAKE) {
    return hostAddresses.firstOrNull()?.canonicalHostName
  }

  return host.canonicalHostName
}
```

maybe you could put a "?" after the host here, because the emulator will crash without it.

```
return host?.canonicalHostName

return host?.hostAddress?.let { listOf(it) } ?: emptyList()
```

**Comment by Napharcos** [comment]
I ran it on a real device, it works.

**Comment by aschulz90** [comment]
I have implemented your suggestions in this branch: https://github.com/Appstractive/dns-sd-kt/tree/fix/txt_resolve_android
Can you please check if that is working as expected on the device? Thanks!

**Comment by Napharcos** [comment]
Unfortunately, I encounter a problem during execution:

> FATAL EXCEPTION: NsdManager
>                                                                                                     Process: com.appstractive.dnssd.androidApp, PID: 9083
>                                                                                                     java.lang.NoClassDefFoundError: Failed resolution of: Lcom/appstractive/dnssd/MDNSDiscover;
>                                                                                                     	at com.appstractive.dnssd.Discovery_androidKt$discoverServices$1$resolveService$1$1.onServiceResolved(Discovery.android.kt:45)
>                                                                                                     	at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:369)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                                     	at android.os.Looper.loop(Looper.java:135)
>                                                                                                     	at android.os.HandlerThread.run(HandlerThread.java:61)
>                                                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appstractive.dnssd.MDNSDiscover" on path: DexPathList[[zip file "/data/app/com.appstractive.dnssd.androidApp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.appstractive.dnssd.androidApp-2/lib/x86_64, /vendor/lib64, /system/lib64]]
>                                                                                                     	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>                                                                                                     	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
>                                                                                                     	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
>                                                                                                     	at com.appstractive.dnssd.Discovery_androidKt$discoverServices$1$resolveService$1$1.onServiceResolved(Discovery.android.kt:45) 
>                                                                                                     	at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:369) 
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                                     	at android.os.Looper.loop(Looper.java:135) 
>                                                                                                     	at android.os.HandlerThread.run(HandlerThread.java:61) 
>                                                                                                     	Suppressed: java.lang.ClassNotFoundException: com.appstractive.dnssd.MDNSDiscover
>                                                                                                     		at java.lang.Class.classForName(Native Method)
>                                                                                                     		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
>                                                                                                     		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
>                                                                                                     		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
>                                                                                                     		... 6 more
>                                                                                                     	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

I don't know what the problem is, because the class is available in the classes2.dex file.

**Comment by aschulz90** [comment]
Strange, it works fine on my device and SDK21 Emulator.

**Comment by Napharcos** [comment]
Then maybe the problem is with me, I just updated it because AGP 8.7.2 was not supported.

**Comment by aschulz90** [comment]
Might be R8 related. When I try to build the app with `isMinifyEnabled = true`, then I get an error:
```
Missing class com.appstractive.dnssd.MDNSDiscover$Result (referenced from: void com.appstractive.dnssd.Discovery_androidKt$discoverServices$1$resolveService$1$1.onServiceResolved(android.net.nsd.NsdServiceInfo))
Missing class com.appstractive.dnssd.MDNSDiscover$TXT (referenced from: void com.appstractive.dnssd.Discovery_androidKt$discoverServices$1$resolveService$1$1.onServiceResolved(android.net.nsd.NsdServiceInfo))
Missing class com.appstractive.dnssd.MDNSDiscover (referenced from: void com.appstractive.dnssd.Discovery_androidKt$discoverServices$1$resolveService$1$1.onServiceResolved(android.net.nsd.NsdServiceInfo))
```

Adding these rules doesn't work though:
```
-keep class com.appstractive.dnssd.MDNSDiscover$Result
-keep class com.appstractive.dnssd.MDNSDiscover$TXT
-keep class com.appstractive.dnssd.MDNSDiscover
```

**Comment by aschulz90** [comment]
I have moved the .java class to a separate module now. That seems to have fixed the issue. Can you check again?

**Comment by aschulz90** [comment]
Version `1.0.3` should be available shortly. Thanks for your help!

**Comment by Napharcos** [comment]
Although the "sample" project works fine, unfortunately when I implement it in my project, it says this during sync:

> Failed to resolve: DNS-SD:lib-java:unspecified
> Affected Modules: composeApp

and this during build:

> Execution failed for task ':composeApp:checkDebugAarMetadata'.
> > Could not resolve all files for configuration ':composeApp:debugRuntimeClasspath'.
>    > Could not find DNS-SD:lib-java:unspecified.
>      Searched in the following locations:
>        - https://repo.maven.apache.org/maven2/DNS-SD/lib-java/unspecified/lib-java-unspecified.pom
>        - file:/C:/Users/user/.m2/repository/DNS-SD/lib-java/unspecified/lib-java-unspecified.pom
>      Required by:
>          project :composeApp > com.appstractive:dns-sd-kt:1.0.3 > com.appstractive:dns-sd-kt-android-debug:1.0.3

Could you try implementing it into another project to see if the issue is on me? Thanks.

**Comment by aschulz90** [comment]
Yes, sorry. lib-java was not inlcuded into the publication. In `1.0.4` it is.
